dist_project=springboot-hello-api
dist_version=0.0.1-SNAPSHOT
dist_dockerJar=springboot-hello-api-server.jar
dist_lib=./lib

harbor_serv=ghcr.io
harbor_pass=CHANGE_ME
harbor_user=CHANGE_ME
harbor_proj=originopenpulse

helm_repos=originopenpulse
helm_versn=1.0.0

k3s_namespace=default
