springfox.documentation.swagger.v2.path=/api-docs
#server.servlet.context-path=/springboot-hello-api/v1
server.servlet.context-path=/
server.port=18081
spring.jackson.date-format=com.wizteco.helloworld.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
